_target_: utils.llm_client.openai.OpenAIClient
base_url: https://api.openai.com/v1
model: gpt-4.1 # LLM model, can also use gpt-4o and other gpt series
temperature: 1.0  # temperature for chat completion
api_key: ${oc.env:OPENAI_API_KEY,null}